apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: instana-eum-key
  namespace: robot-shop
spec:
  encryptedData:
    key: AgBu63bkKIOhY4F9AZF44hlxEG98narytGfDh+IUb/WPItoeJVOLHktYD6ezSfhmEOd3rMarh9TZJ45RZOZ3Tn0UmX/9MoJKgyx3ZxgDcGP5iXiO3p7TeWgQK6egj6oYU3xyOAieJQGAxTFpUtZvFcF/Wotdl761OSHfPnAfF1h6vOIEJm+UNbMnAI18Cea4xHYw738slArrmDl15uMzkX9VWmacek53YHMMelM6fXbFESaHFh6Dyd7YvBouDqHYYTXrMA0HvWNKuFcYSMMTLo5VcoCYMoKN9rxBO+kVXdGUqj/7BMKXU8Z9YgTcFhEHwx0GBh8Ft2d+OaR6imgnjn2ND+NyMtJR4qy8Li9wo5Mqt9YSw1twkUfRXmd43Kj9B2rM1DeuT413FAKF+Gt/JmVQDheNlnp2nJvrF/g9n8cAaKdMi522F3QUvtmi8rCph5PhqMnB/LNSLByIXPgHD6bSfKsLi8Jztnp7WKYYcNMitofiKV9Mkxz3dUZOE38Z6znnWTb6yrjAzZDkd6mnHs3ifEt6m/lB4bRvzx1jgQ1bd72HLy+NECeNCmj7TZnLtFG/7vUhgj8AgH7l0aQkjWmHDnYj8qPL5DWZX4Y9SVq47T7vtrEnaCOA9+0aXShc4EEpf0bE4ubhRaOrNQyRCczEUGdgEWnCDUsgyqPvGdsZuc4ZhGQfkdkzycPoRmccwyzx8DRTdeyE6kkKleR70PyqUTl+yAbz
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: instana-eum-key
      namespace: robot-shop

